linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 3
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - revive
    - gocyclo
    - errcheck
    - staticcheck
    - unused
    - stylecheck
  disable:
    - govet
    - gosec
    - gochecknoinits
    - gochecknoglobals

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
